In [ ]:
#SOL 1.1
import numpy as np
array_1d=np.arange(5,26)
print(array_1d)

[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25]


In [ ]:
#SOL 1.2
array_2d=np.random.randint(10,51,size=(3,4))
print(array_2d)

[[44 29 46 12]
 [27 43 11 26]
 [12 43 11 34]]


In [ ]:
#SOL 2.1
print("1D Array Shape:",array_1d.shape)
print("1D Array Size:",array_1d.size)
print("1D Array Type:",array_1d.dtype)

1D Array Shape: (21,)
1D Array Size: 21
1D Array Type: int64


In [ ]:
#SOL 2.2
print("2D Array Shape:",array_2d.shape)
print("2D Array Size:",array_2d.size)
print("2D Array Type:",array_2d.dtype)

2D Array Shape: (3, 4)
2D Array Size: 12
2D Array Type: int64


In [ ]:
#SOL 3.1
array1=np.array([2,4,6,8,10])
array2=np.array([1,3,5,7,9])

In [ ]:
#SOL 3.2
addition=array1+array2
subtraction=array1-array2
multiplication=array1*array2
division=array1/array2
print("Addition:\n",addition)
print("Subtraction:\n",subtraction)
print("Element wise Multiplication:\n",multiplication)
print("Element wise Division:\n",division)

Addition:
 [ 3  7 11 15 19]
Subtraction:
 [1 1 1 1 1]
Element wise Multiplication:
 [ 2 12 30 56 90]
Element wise Division:
 [2.         1.33333333 1.2        1.14285714 1.11111111]


In [ ]:
#SOL 4.1
array_2d_3x3=np.arange(1,10).reshape(3,3)
print(array_2d_3x3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
#SOL 4.2
broadcasted_array=array_2d_3x3*5
print(broadcasted_array)

[[ 5 10 15]
 [20 25 30]
 [35 40 45]]


In [ ]:
#SOL 5.1
array_4x4=np.arange(10,26).reshape(4,4)
print(array_4x4)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]
 [22 23 24 25]]


In [ ]:
#SOL 5.2
second_row=array_4x4[1,:]
last_column=array_4x4[:,-1]
print("Second Row:\n",second_row)
print("Last Column:\n",last_column)

Second Row:
 [14 15 16 17]
Last Column:
 [13 17 21 25]


In [ ]:
#SOL 5.3
array_4x4[0,:]=0
print(array_4x4)

[[ 0  0  0  0]
 [14 15 16 17]
 [18 19 20 21]
 [22 23 24 25]]


In [ ]:
#SOL 6.1
array_random=np.random.randint(20,41,size=10)
print(array_random)

[28 24 32 29 29 30 40 20 25 28]


In [ ]:
#SOL 6.2
greater_than_30=array_random[array_random>30]
print(greater_than_30)

[32 40]


In [ ]:
#SOL 7.1
array_1d_12=np.arange(11,23)
print(array_1d_12)

[11 12 13 14 15 16 17 18 19 20 21 22]


In [ ]:
#SOL 7.2
array_2d_3x4=array_1d_12.reshape(3,4)
print(array_2d_3x4)

[[11 12 13 14]
 [15 16 17 18]
 [19 20 21 22]]


In [ ]:
#SOL 8.1
matrix_A=np.array([[1,2],[3,4]])
matrix_B=np.array([[5,6],[7,8]])

In [ ]:
#SOL 8.2
matrix_multiplication=np.dot (matrix_A,matrix_B)
transpose_A=matrix_A.T
print("Matrix Multiplication:\n",matrix_multiplication)
print("Transpose of Matrix A:\n",transpose_A)

Matrix Multiplication:
 [[19 22]
 [43 50]]
Transpose of Matrix A:
 [[1 3]
 [2 4]]


In [ ]:
#SOL 9.1
array_random_15=np.random.randint(10,61,size=15)
print(array_random_15)


[57 51 29 45 12 58 17 44 29 22 41 53 58 19 40]


In [ ]:
#SOL 9.2
mean=np.mean(array_random_15)
median=np.median(array_random_15)
std_dev=np.std(array_random_15)
print("Mean:",mean)
print("Median:",median)
print("Standard Deviation:",std_dev)

Mean: 38.333333333333336
Median: 41.0
Standard Deviation: 15.378195241603903


In [ ]:
#SOL 10.1
matrix_A=np.array([[2,1,3],[0,5,6],[7,8,9]])
print(matrix_A)

[[2 1 3]
 [0 5 6]
 [7 8 9]]


In [ ]:
#SOL 10.2
determinant_A=np.linalg.det(matrix_A)
inverse_A=np.linalg.inv(matrix_A)
eigenvalues,eigenvectors=np.linalg.eig(matrix_A)
print("Determinant of Matrix A:",determinant_A)
print("Inverse of Matrix A:",inverse_A)
print("Eigenvalues:\n",eigenvalues)
print("Eigenvectors:\n",eigenvectors)

Determinant of Matrix A: -68.99999999999996
Inverse of Matrix A: [[ 0.04347826 -0.2173913   0.13043478]
 [-0.60869565  0.04347826  0.17391304]
 [ 0.50724638  0.13043478 -0.14492754]]
Eigenvalues:
 [15.45215427  2.40475147 -1.85690573]
Eigenvectors:
 [[-0.22453607 -0.55941438 -0.38300969]
 [-0.48513596  0.7607706  -0.60830181]
 [-0.84511931 -0.3290648   0.69517803]]
